### ISSUE TITLE
publish on npm?

### ISSUE THREAD

**Issue by dirkschumacher** [Planeshifter/ndarray-inv#1]
I am working on a node package for linear regression with `ndarrays` and I am using your package. Do you have any plans to put your package on npm?

https://github.com/dirkschumacher/ndarray-linear-regression

**Comment by dirkschumacher** [comment]
Friendly ping :) @Planeshifter

**Comment by Planeshifter** [comment]
Hi there, no plans to publish on `npm`. Feel free to copy the code and include it in your own project. I am not going to commit any updates to this repository, so you are not going to lose out on anything.

**Comment by dirkschumacher** [comment]
Thanks for the reply. Do you have any problems with forking this project and publishing it on npm under `ndarray-inv`? Alternative is that I could maintain this repository.

**Comment by Planeshifter** [comment]
Added you as an collaborator so you have push access. Feel free to publish to `npm`.

**Comment by dirkschumacher** [comment]
Published it on npm: https://www.npmjs.com/package/ndarray-inv
